version: "3.7"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRESS_DB=mypersonalbudgetplanner
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    depends_on:
      - db
    links:
      - db

volumes:
  pgdata:
    driver: local
  persistent: null
